export const EXAMPLE_ACTION = "EXAMPLE_ACTION";
export const TOGGLE_LOGIN_DISPLAY = "TOGGLE_LOGIN_DISPLAY";
export const TOGGLE_REGISTER_DISPLAY = "TOGGLE_REGISTER_DISPLAY";
export const RSS_FEED_HANDLE_SEARCH_QUERY = "RSS_FEED_HANDLE_SEARCH_QUERY";
export const USER_LOGIN = "USER_LOGIN";
export const SUBMIT_REGISTER = "SUBMIT_REGISTER";
